### PR TITLE
stream.Transform constructor is public

### PR DESCRIPTION
**Pull request by dionjwa**
The constructor for stream.Transform is not private.

### CODE REVIEW

**Comment by nadako** [comment]
But why? Does `Transform` class has any use by itself?

**Comment by dionjwa** [comment]
If you wanted to create a custom Transform class, you would could create an instance then override the _transform method, for example:
https://strongloop.com/strongblog/practical-examples-of-the-new-node-js-streams-api/

**Comment by nadako** [comment]
Yeah, but I wonder if we still want `Transform` ctor to be public, shouldn't the child class provide a public ctor (even if just calling `super`) instead?

**Comment by dionjwa** [comment]
I don't know how you extend externs to child classes. I have looked at doing so for a while, so if you know how that is possible in Haxe, I would really like to know.

**Comment by Gama11** [comment]
@nadako So should this be merged or cloesd? FWIW, it seems like the TS type definitions do allow construction of `Transform`.

**Comment by Gama11** [comment]
Looks like https://github.com/HaxeFoundation/hxnodejs/commit/462c800e16aa0b91df5a7c5d54782b313c3f8730#diff-1d2f8d8b453761fdcd27fd8aee71f60fR39 already made this public.

**Pull request closed without merging**
