### PR TITLE
Added Writable methods

### PR DESCRIPTION
**Pull request by ciscoheat**
* cork
* uncork
* setDefaultEncoding

### CODE REVIEW

**Comment by ciscoheat** [comment]
I'm not sure if those methods should be included in `IWritable`, let me know if not and I'll remove them.

**Comment by nadako** [comment]
Looks good. Looks like this function was there for ages, but apparently it was not documented or something, so I haven't added it.

**Comment by nadako** [comment]
Actually, I was too fast with merging this without looking at CI results, you also need to provide these methods in Duplex! Could you please fix it in an another PR?

**Comment by nadako** [comment]
Nvm, I added them myself.

**Pull request merged**
