### PR TITLE
Fix callback style

### PR DESCRIPTION
**Pull request by terurou**

### CODE REVIEW

**Comment by Gama11** [comment]
What does this fix? Are these arguments just nullable rather than optional?

**Comment by terurou** [comment]
These arguments are Node.js style callback (a.k.a. nodeback). The other modules aren't written by optional argument style.
And I’d like to fix all callback arguments to use `Null<Error> -> ... -> Void`.

**Comment by Gama11** [comment]
>The other modules aren't written by optional argument style.

So this is just meant as a code style consistency fix?

**Comment by terurou** [comment]
> So this is just meant as a code style consistency fix?

Yes

**Comment by Gama11** [comment]
Well, the thing is, these don't mean the same thing. Without `?`, the argument isn't [optional](https://haxe.org/manual/types-function-optional-arguments.html).

```haxe
class Main {
	static function main() {
		var f1:Null<Int>->Void = i -> trace(i);
		var f2:?Int->Void = (?i) -> trace(i);

		f1(0); // 0
		f2(0); // 0

		f1(); // Not enough arguments, expected :Null<Int>
		f2(); // null
	}
}
```

**Comment by terurou** [comment]
> Without ?, the argument isn't optional.

I know that.

These callbacks are called by Node.js side and aren't called Haxe side directly.

**Comment by Gama11** [comment]
I guess it may just be a terminology thing, if something changes the behavior it's not a "code style fix" to me. Anyway, I don't think this really affects much. :)

**Pull request merged**
