### PR TITLE
Applied Event abstract on Cluster events

### PR DESCRIPTION
**Pull request by fantoine**

### CODE REVIEW

**Comment by clemos** [comment]
:+1: despite CI failing :p

**Comment by fantoine** [comment]
The fail is not my fault :) It seems doc-deploy.sh is broken on "Haxe: development" target.

**Comment by fantoine** [comment]
Any news on this?

**Comment by nadako** [comment]
Thanks. Though I wonder if `message` event listener type should be `Dynamic->Dynamic->Void` similar to one in `ChildProcessEvent`, since the docs says it's the same event.

**Comment by fantoine** [comment]
After looking deeper on the documentation, i think you're right... sorry about this.

**Comment by nadako** [comment]
>  It seems doc-deploy.sh is broken on "Haxe: development" target.

@andyli is there an easy way to make travis execute `bash doc-deploy.sh` only when it builds from the main repo (and thus skip forks and prs)?

**Comment by andyli** [comment]
I would recommend to detect the present of secure variables (`GH_TOKEN`) and only proceed to deploy when they are there.
The secure vars are only present for the builds from main repo, and not available for forks and prs.
There is an extra benefit in this method - people can override `GH_TOKEN` and `GH_REF` in their fork such that they can deploy to the gh page of their own fork.

**Comment by nadako** [comment]
Thanks, I'll look into it.

**Pull request merged**
