### PR TITLE
Prevent clashes with Haxe 4's `final` keyword

### PR DESCRIPTION
**Pull request by jonasmalacofilho**

### CODE REVIEW

**Comment by Simn** [comment]
Thanks!

**Comment by jonasmalacofilho** [comment]
: )

Wow, you were so fast I didn't even manage to fix the missing description in time!

[I opened the PR from the command line]

**Comment by nadako** [comment]
Hmm, we should think about some consistent way to name things that clash with haxe keywords...

**Comment by jonasmalacofilho** [comment]
I was also wondering how would I deal with

```
typedef Foo = {
   final:Bar
}
```

Can we even use `@:native` there?

**Comment by nadako** [comment]
I think not, at least not without weird limitations, this was discussed somewhere and is still an issue I think. I remember @clemos macro-generating an abstract to support that that generates get/set properties for incompatible `@:native` fields.

**Pull request merged**
