### PR TITLE
add missing methods which are causing issues in haxe.zip.Reader

### PR DESCRIPTION
**Pull request by peteshand**

### CODE REVIEW

**Comment by Gama11** [comment]
Does this really help with anything? Looks like it will just lead to a runtime error as soon as you call the constructor.

**Comment by peteshand** [comment]
Yeah it's stops a compile error. 

In the std lib, haxe.zip.Reader calls 
```new Uncompress```, which throws an error. This bug was reported quite a while ago, so would be good to resolve it

**Comment by Gama11** [comment]
But it doesn't look like this actually solves anything, it just moves the error from compile time to runtime?

**Comment by peteshand** [comment]
Hmm that's not entirely true, It moves the error from always happening, to only happening when you call a particular method on Reader. For example I'm not user Reader, but because of this in compatibility my whole app won't compile .

**Comment by Gama11** [comment]
Hm, I see... Do you have a code example?

**Comment by peteshand** [comment]
It's GMT+10 so not at my computer. But basically hxnodejs overrides a std class and removes a bunch of methods, this is going to causes, should need a code example to understand this. Could you just merge please

**Comment by Gama11** [comment]
Calm down. :) It's not about understanding, I was thinking it would make for a good test case for unit tests / CI. But it looks like I misremembered and we don't actually have unit tests for hxnodejs, just these [examples](https://github.com/HaxeFoundation/hxnodejs/tree/master/examples).

**Comment by nadako** [comment]
It's probably fine to merge this, tho for `Uncompress` you can probably use [this code](https://github.com/HaxeFoundation/hxnodejs/issues/118#issuecomment-472488429).

**Comment by peteshand** [comment]
Thanks

**Pull request merged**
