### PR TITLE
Suppress some deprecated warnings.

### PR DESCRIPTION
**Pull request by terurou**
Suppress these:

```
src/js/node/Url.hx:61: characters 32-41 : Warning : This typedef is deprecated in favor of { ?slashes : Null<Bool>, ?search : Null<String>, ?query : Null<haxe.extern.EitherType<String, haxe.DynamicAccess<String>>>, ?protocol : Null<String>, ?port : Null<String>, ?pathname : Null<String>, ?path : Null<String>, ?href : Null<String>, ?hostname : Null<String>, ?host : Null<String>, ?hash : Null<String>, ?auth : Null<String> }
src/js/node/Url.hx:83: characters 91-100 : Warning : This typedef is deprecated in favor of { ?slashes : Null<Bool>, ?search : Null<String>, ?query : Null<haxe.extern.EitherType<String, haxe.DynamicAccess<String>>>, ?protocol : Null<String>, ?port : Null<String>, ?pathname : Null<String>, ?path : Null<String>, ?href : Null<String>, ?hostname : Null<String>, ?host : Null<String>, ?hash : Null<String>, ?auth : Null<String> }
src/js/node/domain/Domain.hx:34: characters 24-35 : Warning : This typedef is deprecated in favor of { domainThrown : Bool, domainEmitter : js.node.events.IEventEmitter, domainBound : haxe.Function, domain : js.node.domain.Domain }
```

### CODE REVIEW

**Comment by Gama11** [comment]
I don't really get it... why would you add a filter to suppress warnings that originate in this library (rather than just remove the `@:deprecated`?).

**Comment by terurou** [comment]
@Gama11 Thanks for your comment. I closed this PR and report https://github.com/HaxeFoundation/haxe/issues/9069.

**Comment by Gama11** [comment]
Well, I think I misunderstood what this does exactly. It looks like it only blocks these warnings when they occur within hxnodejs, not in user code?

**Comment by terurou** [comment]
> they occur within hxnodejs, not in user code?
Yes. (I'm sorry for my poor explanation...

**Pull request merged**
