### PR TITLE
Update to js.lib.*

### LINKED ISSUE #122: Some `js.*` types moved to `js.lib.*`
See https://github.com/HaxeFoundation/haxe/pull/7390
hxnodejs needs to be updated.

### PR DESCRIPTION
**Pull request by RealyUniqueName**
Closes #122

### CODE REVIEW

**Comment by Gama11** [comment]
Hm, CI is still failing, even though I've just restarted the Haxe dev job. Looks like it's using a Haxe version from yesterday still:

>$ echo $(haxe -version)
4.0.0-rc.2+2f98d03

@andyli I know you've tried something to help with that, any ideas?

**Comment by andyli** [comment]
The `DEPLOY_NIGHTLIES=1` job (the first one) of your commit fail: https://travis-ci.org/HaxeFoundation/haxe/builds/521135645

**Comment by Gama11** [comment]
Oh, that makes sense. So maybe it's working fine after all now. 👍

**Comment by Gama11** [comment]
Merging anyway, since locally it works fine with latest Haxe + these changes.

**Pull request merged**
