### PR TITLE
Update haxelib.json

### PR DESCRIPTION
**Pull request by markknol**
Add HaxeFoundation as user

### CODE REVIEW

**Comment by Gama11** [comment]
I'm not sure this is gonna work, the first person in the list is special / must be the original contributor, right?

Also, I guess this means @nadako has to make the next release.

**Comment by nadako** [comment]
Huh, I didn't know that...

**Comment by markknol** [comment]
Me neither, should I put it as last user?

**Comment by Gama11** [comment]
I'm not 100% sure about it, maybe the "main contributor" can also change the main contributor. But you definitely can't add new contributors as a "secondary contributor".

**Pull request merged**
