### PR TITLE
added 'rawHeaders' and 'statusMessage' properties

### PR DESCRIPTION
**Pull request by clue4gd**

### CODE REVIEW

**Comment by nadako** [comment]
Thanks! I wonder though when was that added to the docs and whether there are more. I guess I'll have to go through node.js API again.

**Comment by clue4gd** [comment]
No worries! If i find more, i will let you know. ;) Could you may be tag the changes, so we could use them via haxelib. Thanks in advance.

**Comment by nadako** [comment]
I wanted to look for more APIs, but I don't have too much time atm, so I'll just make a release with your changes.

**Comment by clue4gd** [comment]
Cool, thanks!

**Pull request merged**
