### PR TITLE
added basic, incomplete compress/uncompress implementation

### PR DESCRIPTION
**Pull request by clemos**
to be completed...

### CODE REVIEW

**Comment by nadako** [comment]
I believe there's a problem described in #42 with this.

**Comment by ncannasse** [comment]
please remove the traces :)
@nadako not sure which problem, if the API is correctly respected. Of course, it will be nice to have progressive (un)compress support as well

**Comment by nadako** [comment]
@ncannasse the problem of these implementation overshadowing one in std, so macros don't work.

**Comment by clemos** [comment]
I just removed the traces.
Honestly, I would definitely implement the rest of the API in both PHP and JS, if only it had some documentation and / or unit tests...

**Comment by kevinresol** [comment]
copyright year should be 2015 :stuck_out_tongue:

**Comment by ncannasse** [comment]
@nadako ah right, macros. But that can be addressed by merging haxe/std/neko/_std/haxe/zip implementation into it (with #if neko)

**Comment by nadako** [comment]
yeah but that's not good for obvious reasons of code duplication and maintainance, so I'd really like to see some "proper" solution for that

**Comment by ncannasse** [comment]
@nadako see https://github.com/HaxeFoundation/haxe/issues/4249

**Comment by nadako** [comment]
As @Simn pointed out, we could try placing these files in `js/_std/haxe/zip` and see if it works.

**Comment by Gama11** [comment]
This seems obsolete after #160 (plus there's merge conflicts).

**Pull request closed without merging**
